/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.uv.programa07;

/**
 *
 * @author Rodrigo Mencías
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MNUSalir = new javax.swing.JMenuItem();
        MNUVentas = new javax.swing.JMenu();
        menVentas = new javax.swing.JMenuItem();
        mnuproductos = new javax.swing.JMenu();
        menProductos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Inicio");

        MNUSalir.setText("Salir");
        MNUSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNUSalirActionPerformed(evt);
            }
        });
        jMenu1.add(MNUSalir);

        jMenuBar1.add(jMenu1);

        MNUVentas.setText("Procesos");

        menVentas.setText("Ventas");
        menVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menVentasActionPerformed(evt);
            }
        });
        MNUVentas.add(menVentas);

        jMenuBar1.add(MNUVentas);

        mnuproductos.setText("Catalogo");

        menProductos.setText("Productos");
        menProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProductosActionPerformed(evt);
            }
        });
        mnuproductos.add(menProductos);

        jMenuBar1.add(mnuproductos);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MNUSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNUSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MNUSalirActionPerformed

    private void menVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menVentasActionPerformed
        Ventas ventas = new Ventas();
        ventas.setVisible(true);
        jDesktopPane1.add(ventas);
    }//GEN-LAST:event_menVentasActionPerformed

    private void menProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProductosActionPerformed
        Productos productos = new Productos();
        productos.setVisible(true);
        jDesktopPane1.add(productos);
    }//GEN-LAST:event_menProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MNUSalir;
    private javax.swing.JMenu MNUVentas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menProductos;
    private javax.swing.JMenuItem menVentas;
    private javax.swing.JMenu mnuproductos;
    // End of variables declaration//GEN-END:variables
}
